# Test your FastAPI endpoints

GET http://127.0.0.1:8000/Top10
Accept: application/json

###

GET http://127.0.0.1:8000/RecomendationByGenre/{genre}
Accept: application/json

###

GET http://127.0.0.1:8000/UpdateRecomendationByUser/{userid}
Accept: application/json

###
